### ISSUE TITLE
More datasets ideas

### ISSUE THREAD

**Issue by arthurdouillard** [Continvvm/continuum#196]
- [ ] Food101, classif, implem in #191 
- [X] CIFAR10
- [X] CIFAR100 
- [ ] Birdsnap, must improve the crawler with multi-threading and python3 
- [ ] SUN397
- [ ] Stanford Cars
- [ ] FGVC Aircraft
- [ ] Pascal VOC 2007 classif
- [X] Describable Textures DTD
- [ ] Oxford pets
- [ ] Caltech 101, Caltech 256, implem in #189 
- [ ] Oxford flowers 102
- [X] MNIST
- [ ] Facial emotion reco 2013
- [ ] STL10, implem in #186 
- [ ] EuroSAT
- [ ] RESISC45
- [ ] GTSRB
- [ ] KITTI, need to have support of object detection. Btw how to handle scenario? Like in segmentation (overlap/disjoint)? See #194 
- [ ] Country211
- [ ] PatchCamelyon
- [ ] UCF101
- [ ] Kinetics700
- [ ] CLEVR Counts
- [ ] Hateful Memes
- [ ] Rendered SST2
- [X] ImageNet

**Comment by arthurdouillard** [comment]
Md Rifat Arefin on Oxford flowers & Oxfords pets

**Comment by arthurdouillard** [comment]
I'm taking eurosat and sun397
